site_name: MkLorum
nav:
  - Home: index.md
  - About: about.md
  - Info: info.md

theme:
  name: mkdocs
  locale: en
  highlightjs: false

site_dir: src/resources/odc/help
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
