[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "odc-commander"
version = "0.2.0"
description = "Control the Open Dynamic Clamp Hardware"
authors = ["Leonardo Covarrubias <leo@leocov.com>"]
license = "CC BY 4.0"
readme = "README.md"
packages = [
    { include = "odc_commander", from = "src" },
]

[tool.poetry.dependencies]
python = "3.11.*"
pyside6 = "6.7.*"
cobs = "1.*"
loguru = "0.*"
pyside-app-core = {path = "../pyside-app-core", develop = true}

[tool.poetry.group.dev.dependencies]
mypy = "1.*"
black = "24.*"
jinja2 = "3.*"

[tool.poetry.group.debug.dependencies]
pyserial = "*"

# ------------------------------
# linting
[tool.black]

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"
packages = ["odc_commander"]
strict = true
implicit_reexport = true