[tool.poetry]
name = "odc-commander"
version = "0.1.0"
description = "Control the Open Dynamic Clamp Hardware"
authors = ["Leonardo Covarrubias <leo@leocov.com>"]
license = "CC BY 4.0"
readme = "README.md"
packages = [
    { include = "odc_commander", from = "src" },
    { include = "core_plus", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pyside6 = { version = "^6.6.3.1", python = ">=3.11,<3.13" }
cobs = "^1.2.1"
loguru = "^0.7.2"
pyside-app-core = "^0.2.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
black = "^24.3.0"
jinja2 = "^3.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

