name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

permissions:
  contents: read

jobs:


  # -------------
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: System Dependencies
        run: >-
          sudo apt-get update && 
          sudo apt-get install -y 
          libxcb-xinerama0 
          libxkbcommon-x11-0 
          libgl1-mesa-glx 
          libegl1 
          libopengl0
          libxcb-icccm4 
          libxcb-image0 
          libxcb-keysyms1 
          libxcb-randr0 
          libxcb-render-util0 
          libxcb-xinerama0 
          libxcb-xfixes0 
          x11-utils 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Checks
        run: pipx run hatch fmt --check


  # -------------
  build:
    name: Build Smoke Test (${{ matrix.os }})
    needs: [ test ]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: System Dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: >-
          sudo apt-get update && 
          sudo apt-get install -y 
          libxcb-xinerama0 
          libxkbcommon-x11-0 
          libgl1-mesa-glx 
          libegl1 
          libopengl0
          libxcb-icccm4 
          libxcb-image0 
          libxcb-keysyms1 
          libxcb-randr0 
          libxcb-render-util0 
          libxcb-xinerama0 
          libxcb-xfixes0 
          x11-utils 

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Release Build
        run: pipx run hatch -v build -t pyside-app

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "odc-commander-${{ matrix.os }}"
          path: dist
