name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

permissions:
  contents: read

jobs:


  # -------------
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Checks
        run: pipx run hatch fmt --check


  # -------------
  build:
    name: Build Smoke Test (${{ matrix.os }})
    needs: [ test ]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Compile RCC
        run: pipx run hatch run compile-rcc

      - name: Release Build
        run: pipx run hatch run release-build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "odc-commander-${{ matrix.os }}"
          path: dist
