name: Continuous Integration
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build Smoke Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - run: pipx install hatch

      - name: Compile RCC
        run: hatch run compile-rcc

      - name: Release Build
        run: hatch run release-build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "odc-commander-${{ matrix.os }}"
          path: dist